### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by trmendes** [ctrlaltdel/Cowsay-android#1]
It would be nice to hacve cowsay-android at the f-droid app repository :)

https://gitlab.com/fdroid/rfp/issues/new

**Comment by rorist** [comment]
Hello,

There was at some point but it looks it's been removed ^^

https://f-droid.org/wiki/page/ch.fixme.cowsay

**Comment by trmendes** [comment]
Shall we open an issue to have it again? It seems like the app isn't the anymore because:

* This app has the Disabled Algorithm Antifeature.
* This app has the KnownVuln Antifeature.
